name: drinks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  sizer: ^3.0.4
  easy_splash_screen: ^1.0.4
  flutter_branch_sdk: ^8.3.1
  share_plus: ^10.0.3
  url_launcher: ^6.3.1
  syncfusion_flutter_datepicker: ^27.1.58
  numberpicker: ^2.1.2
  google_mobile_ads: ^5.2.0
  connectivity_plus: ^6.1.1






dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0
  # analyzer: ^4.7.0 
  hive_generator: ^1.1.1



flutter:
  uses-material-design: true

  assets:
    - assets/png/


flutter_native_splash:
  image: assets/png/wine.png 